version: "3"

tasks:
  deps:
    desc: Install backend and frontend dependencies
    deps:
      - deps:backend
      - deps:frontend
  deps:backend:
    desc: Install backend Go dependencies
    cmds:
      - go mod download
  deps:frontend:
    desc: Install frontend dependencies
    dir: web
    cmds:
      - corepack enable pnpm
      - pnpm install
  deps:air:
    desc: Install air for backend reloads
    cmds:
      - go install github.com/air-verse/air@latest
  docs:api:
    desc: Generate OpenAPI docs with swag
    deps:
      - deps:backend
    cmds:
      - go run github.com/swaggo/swag/cmd/swag@v1.16.3 init -g docs.go -o internal/server/docs --dir cmd/server,internal/server --parseDependency --parseInternal
  build:web:
    desc: Build frontend assets
    deps:
      - deps:frontend
    dir: web
    cmds:
      - pnpm build
      - rm -rf ../internal/server/static
      - mkdir -p ../internal/server/static
      - cp -R dist/. ../internal/server/static/
  build:
    desc: Build embeddedFS production binary
    deps:
      - deps:backend
      - build:web
      - docs:api
    cmds:
      - go build -tags embedfs -o build/planemgr ./cmd/server  
  dev:backend:
    desc: Start backend dev server
    deps:
      - deps:backend
      - deps:air
    cmds:
      - air
  dev:frontend:
    desc: Start frontend dev server
    dir: web
    cmds:
      - pnpm dev
  dev:
    desc: Install dependencies and start dev servers
    deps:
      - deps
    cmds:
      - cmd: task -p dev:backend dev:frontend
