// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chart": {
            "get": {
                "description": "Lists all available charts.",
                "tags": [
                    "chart"
                ],
                "summary": "List charts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.chartListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new chart.",
                "tags": [
                    "chart"
                ],
                "summary": "Create chart",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.chartResponse"
                        }
                    }
                }
            }
        },
        "/chart/{id}": {
            "get": {
                "description": "Returns the contents of a file in a chart at a ref.",
                "tags": [
                    "chart"
                ],
                "summary": "Get chart file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path in the chart repo",
                        "name": "file",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Git ref (defaults to HEAD)",
                        "name": "ref",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.chartFileResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Writes files to a chart and commits the change.",
                "tags": [
                    "chart"
                ],
                "summary": "Update chart files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Commit payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.chartCommitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.chartCommitResponse"
                        }
                    }
                }
            },
            "head": {
                "description": "Returns a recursive listing of files for a chart at a ref.",
                "tags": [
                    "chart"
                ],
                "summary": "List chart files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Git ref (defaults to HEAD)",
                        "name": "ref",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.chartTreeResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the API status.",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.healthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.chartCommitRequest": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.chartFileUpdate"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "server.chartCommitResponse": {
            "type": "object",
            "properties": {
                "chartId": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "server.chartFileResponse": {
            "type": "object",
            "properties": {
                "chartId": {
                    "type": "string"
                },
                "contents": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "server.chartFileUpdate": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "server.chartListResponse": {
            "type": "object",
            "properties": {
                "chartIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.chartResponse": {
            "type": "object",
            "properties": {
                "chartId": {
                    "type": "string"
                }
            }
        },
        "server.chartTreeResponse": {
            "type": "object",
            "properties": {
                "chartId": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "server.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Plane Manager API",
	Description:      "Plane Manager HTTP API for chart and workspace operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
