// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chart": {
            "get": {
                "description": "Lists all available charts.",
                "tags": [
                    "chart"
                ],
                "summary": "List charts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.chartListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new chart.",
                "tags": [
                    "chart"
                ],
                "summary": "Create chart",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_server.chartListResponse"
                        }
                    }
                }
            }
        },
        "/chart/{id}": {
            "get": {
                "description": "Returns a single chart and its nodes.",
                "tags": [
                    "chart"
                ],
                "summary": "Get chart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.chartResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a chart.",
                "tags": [
                    "chart"
                ],
                "summary": "Delete chart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "description": "Applies node updates to a chart.",
                "tags": [
                    "chart"
                ],
                "summary": "Update chart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chart ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.chartResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the API status.",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.healthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_server.chartListResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_server.chartResponse": {
            "type": "object",
            "properties": {
                "chartId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_server.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Plane Manager API",
	Description:      "Plane Manager HTTP API for chart and workspace operations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
